EXERCICIOS_PERMITIDOS = [
    "Polichinelo",
    "Agachamento livre",
    "Prancha",
    "Flexão de braço com joelhos apoiados",
    "Abdominal tradicional",
    "Caminhada leve ou subida de escada",
    "Alongamento de corpo inteiro",
    "Afundo",
    "Abdominal",
    "Prancha lateral",
    "Flexão de braço normal",
    "Elevação de quadril",
    "Mountain climber",
    "Alongamento com foco em quadril e pernas",
    "Agachamento com halteres",
    "Pular corda",
    "Rosca direta com elástico ou halter",
    "Abdominal infra com pernas elevadas",
    "Prancha com toque no ombro",
    "Step-up em banco ou cadeira",
    "Alongamento de costas e mobilidade torática",
    "Flexão diamante",
    "Agachamento sumô com peso",
    "Burpee",
    "Stiff",
    "Elevação lateral de ombro",
    "Hip thrust com peso",
    "Prancha com elevação de braço",
    "Saltos laterais",
    "Alongamento completo e relaxamento"
]